name: Workflow cleanup

on:
  schedule:
    - cron: '0 0 * * 4'  # Every Thursday at midnight UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Old Workflows Runs
        uses: gesslar/workflow-run-cleaner@v1.9.2
        with:
          token: ${{ github.token }}
          repo-owner: ${{ github.repository_owner }}
          target-cleanup-repos: 'magmanu/github-action-bot-signed-commit'
      
      - name: Remove Testing Branches
        uses: fpicalausa/remove-stale-branches@v2.4.0
        with:
          restrict-branches-regex: ^qa-.*$
          days-before-branch-stale: 7
          days-before-branch-delete: 7

