name: Workflow cleanup

on:
  schedule:
    - cron: '0 0 * * 4'  # Every Thursday at midnight UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow Cleanup Action
        uses: gesslar/workflow-run-cleaner@v1.9.2
        with:
          token: ${{ github.token }}
          repo-owner: ${{ github.repository_owner }}
          target-cleanup-repos: 'magmanu/github-action-bot-signed-commit'

