name: Autodoc
on:
 repository_dispatch:
    types: [my-event]

permissions:
  contents: write

jobs:
  document-github-action:
    runs-on: ubuntu-latest
    name: Document GitHub action
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Generate action docs
        uses: tjtharrison/github-actions-docs@1.3.1
