name: Autodoc
on:
  repository_dispatch:
    types: [action_test]

permissions:
  contents: write

jobs:
  document-github-action:
    runs-on: ubuntu-latest
    name: Document GitHub action
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Generate action docs
        uses: tjtharrison/github-actions-docs@1

