on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  document-github-action:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Commit with bot verified commit
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create list of files to sign
        run: |
          git fetch origin qa
          echo "$(git diff --name-only origin/qa...HEAD)" > file_list.txt
          cat file_list.txt

          git rev-parse --abbrev-ref HEAD 

      - name: Test action
        id: test
        uses: ./
        with:
          TARGET_REF: qa
          FILE_LIST: file_list.txt

      - name: Validate commit
        run: |
          # Get the latest commit SHA from the target branch
          latest_commit_sha=$(gh api repos/${{ github.repository }}/git/ref/heads/$TARGET_REF --jq '.object.sha')
          
          if [[ "$latest_commit_sha" == ${{ steps.test.outputs.sha }} ]]; then
            echo "The commit was succesfully pushed to the target ref."
          else
            echo "Failure to push the commit to the target ref."
            exit 1
          fi
          
          if git log -1 --pretty=format:'%G?' | grep -q 'G'; then
            echo "Commit is successfully signed and verified."
          else
            echo "Failure to sign or verify commit."
            exit 1
          fi
          